
parameters:
  name: ''
  pool: ''
  customMatrixes: ''  


jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 9000
  cancelTimeoutInMinutes: 200
  pool: 
    name: ${{ parameters.pool }}
  strategy:
    matrix:
      ${{ insert }}: ${{parameters.customMatrixes}}
  
  steps:
  - bash: |
      nvidia-smi
    displayName: "dump nvidia-smi"
    condition: startsWith(variables['DEVICE_TYPE'], 'cu')

  - script: |
    
      azcopy copy "https://sunghchostorageaccount.blob.core.windows.net/test/model_publish/$(MODEL_NAME)" --recursive $(Build.BinariesDirectory)
    workingDirectory: $(Build.SourcesDirectory)
    displayName: "Download ONNX model from azure blob"


  - script: |
      baseline_model_folder=`find $(Build.BinariesDirectory)/oga_models/ -name config.json -printf "%h\n"`

      echo "baseline_model folder: $baseline_model_folder"
      
      docker run --gpus all --rm \
          --ipc=host \
          --volume $(Build.SourcesDirectory):/ort_src \
          --volume $(Build.BinariesDirectory):/build \
          -e CCACHE_DIR=/cache -w /ort_src \
          ptebic.azurecr.io/public/aifx/acpt/stable-ubuntu2004-cu121-py310-torch222:biweekly.202410.2 /bin/bash /perf/model_perf_script-${DEVICE_TYPE}.sh
    workingDirectory: $(Build.SourcesDirectory)
    displayName: "start baseline model endpoint and RAI eval in container"
    # condition: eq(${{ parameters.run_baseline_model }}, 'true')

  # - task: AzureCLI@2
  #   displayName: 'upload model to Blob Storage'
  #   inputs:
  #     azureSubscription: AIInfraBuild
  #     scriptLocation: inlineScript
  #     scriptType: bash
  #     inlineScript: |
  #       cd $(Build.BinariesDirectory)
  #       azcopy copy './oga_models' 'https://sunghchostorageaccount.blob.core.windows.net/test/${{ parameters.model_name }}' --recursive
