stages:

# CPU Test
# ================================
- stage: ONNXConverterCPU
  displayName: ONNX CPU Model Conversion
  dependsOn: []
  jobs:
  - template: .github/job_templates/converter_template.yml
    parameters:
      name: ONNX_Converter_CPU
      pool: $(BUILD_POOL_LIN_CPU)
      customMatrixes:
        ONNX_CONVERTER:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cpu"
          DATA_TYPE: "int4"

- stage: PerformanceTestForCPU
  displayName: ONNX CPU Model Performance Test
  dependsOn: ONNXConverterCPU
  condition: succeeded()
  jobs:
  - template: .github/job_templates/perf_template.yml
    parameters:
      name: ONNX_CPU_Performance_Test
      pool: $(BUILD_POOL_LIN_CPU)
      customMatrixes:
        CPU_ONNX_PERF:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cpu"
          DATA_TYPE: "int4"

- stage: AccuracyTestForCPU
  displayName: ONNX CPU Model Accuracy Test
  dependsOn: ONNXConverterCPU
  condition: succeeded()
  jobs:
  - template: .github/job_templates/accuracy_template.yml
    parameters:
      name: ONNX_CPU_Accuracy_Test
      pool: $(BUILD_POOL_LIN_CPU)
      customMatrixes:
        CPU_ONNX_ACCURACY:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cpu"
          DATA_TYPE: "int4"

- stage: RAITestForCPU
  displayName: ONNX CPU Model RAI Test
  dependsOn: ONNXConverterCPU
  condition: succeeded()
  jobs:
  - template: .github/job_templates/rai_template.yml
    parameters:
      name: ONNX_CPU_RAI_Test
      pool: $(BUILD_POOL_LIN_CPU)
      customMatrixes:
        CPU_ONNX_RAI:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cpu"
          DATA_TYPE: "int4"

# CUDA Test
# ================================
- stage: ONNXConverterGPU
  displayName: ONNX GPU Model Conversion
  dependsOn: []
  jobs:
  - template: .github/job_templates/converter_template.yml
    parameters:
      name: ONNX_Converter_CUDA
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        ONNX_CONVERTER:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cuda"
          DATA_TYPE: "int4"

- stage: PerformanceTestForGPU
  displayName: ONNX GPU Model Performance Test
  dependsOn: ONNXConverterGPU
  condition: succeeded()
  jobs:
  - template: .github/job_templates/perf_template.yml
    parameters:
      name: ONNX_GPU_Performance_Test
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        CPU_ONNX_PERF:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cuda"
          DATA_TYPE: "int4"

- stage: AccuracyTestForGPU
  displayName: ONNX GPU Model Accuracy Test
  dependsOn: ONNXConverterGPU
  condition: succeeded()
  jobs:
  - template: .github/job_templates/accuracy_template.yml
    parameters:
      name: ONNX_GPU_Accuracy_Test
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        GPU_ONNX_ACCURACY:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cuda"
          DATA_TYPE: "int4"

- stage: RAITestForGPU
  displayName: ONNX GPU Model RAI Test
  dependsOn: ONNXConverterGPU
  condition: succeeded()
  jobs:
  - template: .github/job_templates/rai_template.yml
    parameters:
      name: ONNX_GPU_RAI_Test
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        GPU_ONNX_RAI:
          _MODEL_NAMES: $(MODEL_NAMES)
          DEVICE_TYPE: "cuda"
          DATA_TYPE: "int4"

# PyTorch test
# ================================

- stage: PerformanceTestForTorch
  displayName: Torch Model Performance Test
  dependsOn: []
  jobs:
  - template: .github/job_templates/perf_template.yml
    parameters:
      name: Torch_Performance_Test
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        GPU_Torch_PERF:
          _MODEL_NAMES: $(MODEL_NAMES)

- stage: AccuracyTestForTorch
  displayName: Torch Model Accuracy Test
  dependsOn: PerformanceTestForTorch
  condition: succeeded()
  jobs:
  - template: .github/job_templates/accuracy_template.yml
    parameters:
      name: Torch_Accuracy_Test
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        GPU_Torch_ACCURACY:
          _MODEL_NAMES: $(MODEL_NAMES)

- stage: RAITestForTorch
  displayName: Torch Model RAI Test
  dependsOn: AccuracyTestForTorch
  condition: succeeded()
  jobs:
  - template: .github/job_templates/rai_template.yml
    parameters:
      name: Torch_RAI_Test
      pool: $(BUILD_POOL_LIN_GPU)
      customMatrixes:
        GPUT_Torch_RAI:
          _MODEL_NAMES: $(MODEL_NAMES)